import fs from 'fs';
import path from 'path'
import matter from 'gray-matter'

import Navbar from '@/Components/Navbar'
import Head from 'next/head'
import searchimg from '../pages/img/white_search.png'
import Image from 'next/image'
import Link from 'next/link'
import Card from '@/Components/Card'
export default function Home({posts}) {
return (
<>
<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>
<Navbar/>  

<div class="hero">


{/* hero starts here */}
<div className="search-box">
<h1 id="he-h1">We will find you the perfect getaway</h1>

<form >
<input type="text" placeholder="Find your next Destination! "/>
<button className="form-btn" type="submit">
<Image src={searchimg} width={14} alt='...' priorty />
</button>
</form>
</div>
</div>
{/* hero stops here */}

{/* plan starts here */}
<div className="plan-box">

<div className="left-plan">
<h1 style={{padding:'0 20px'}}>Plan Your Adventure</h1>
<p style={{padding:'0 20px'}}>
Are you ready to embark on your next journey? Let us help you plan the adventure of a lifetime! Our website offers a wide range of travel resources to help you make the most of your trip. 
</p>

<ul style={{padding:'0 20px'}}>
<li>Search for flights, hotels, and activities</li>
<li>Read travel guides and insider tips</li>
<li>Save your favorite destinations and itineraries</li>
<li>Get up-to-date information on travel restrictions and health and safety measures</li>
</ul>
</div>

<div className="right-plan">
<h1 style={{padding:'0 20px'}}>Featured Destinations</h1>
<p style={{padding:'0 20px'}}>
Looking for inspiration for your next trip? Check out some of our top featured destinations below!
</p>
<ul style={{padding:'0 20px'}}>
<li><Link href="#">Bali, Indonesia</Link></li>
<li><Link href="#">Paris, France</Link></li>
<li><Link href="#">Machu Picchu, Peru</Link></li>
<li><Link href="#">Santorini, Greece</Link></li>
</ul>
</div>

</div>
{/* <!-- plan stops here --> */}

<div className="tropic-hero">

<div className="tropic-hero-title">

<h1 style={{
color:'#fff',
fontSize:'5rem',
textAlign:'center'
}}>Tropical vacation awaits</h1>
</div>

</div>

<h1 style={{
color:'grey',
borderBottom:'1px solid grey',
lineHeight:'2',
textTransform:'capitalize',
padding:'0 1rem'
}}>headline news</h1>

<div className='card-grid'>
{posts && posts.map((post, index) => (
<Card key={index} post={post}/>
))}
</div>
</>
)
}

export async function getStaticProps() {
// Get files from the feartered articles dir
const files = await fs.promises.readdir('Articles');

// Get slug and frontmatter from blogs
const posts = await Promise.all(
files.map(async (filename) => {
// Create slug
const slug = filename.replace('.md', '');
  
 // articles block
const markdownWithMeta = await fs.promises.readFile(
path.join('Articles', filename),
'utf-8');
  
const { data: frontmatter } = matter(markdownWithMeta);
return {
slug,
frontmatter,
};
})
);
// articles block
 


// posts.sort((a, b) => new Date(a.frontmatter.date) - new Date(b.frontmatter.date));
return {
props: {
posts,

},
};
}