import fs from 'fs';
import path from 'path'
import matter from 'gray-matter'
import Head from 'next/head'
import React from 'react'
import Card from '@/Components/Card'
import Footer from '@/Components/Footer'
import Navbar from '@/Components/Navbar'
import FeaturedCard from '@/Components/FeaturedCard';


const TravelNews = ({posts,featuredposts}) => {
return (
<>
<Head>
<title>Journey</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>
<Navbar/>
{featuredposts && featuredposts.map((post, index) => (
<FeaturedCard key={index} post={post}/>
))}
<div className='card-grid'>
{posts && posts.map((post, index) => (
<Card key={index} post={post}/>
))}
</div>
<Footer/>
</>
)
}

export default TravelNews


export async function getStaticProps() {
// Get files from the feartered articles dir
const files = await fs.promises.readdir('TravelArticles');
const featuredFiles = await fs.promises.readdir('FeaturedArticles');

// Get slug and frontmatter from blogs
const posts = await Promise.all(
files.map(async (filename) => {
// Create slug
const slug = filename.replace('.md', '');
  
 // articles block
const markdownWithMeta = await fs.promises.readFile(
path.join('TravelArticles', filename),
'utf-8');
  
const { data: frontmatter } = matter(markdownWithMeta);
return {
slug,
frontmatter,
};
})
);
// articles block

// featured articles block
const featuredposts = await Promise.all(
featuredFiles.map(async (filename) => {
// Create slug
const slug = filename.replace('.md', '');
  
// Get frontmatter
const markdownWithMeta = await fs.promises.readFile(
path.join('FeaturedArticles', filename),
'utf-8'
);
  
const { data: frontmatter } = matter(markdownWithMeta); 
return {
slug,
frontmatter,
};
})
);
// featured articles block
 


posts.sort((a, b) => new Date(a.frontmatter.date) - new Date(b.frontmatter.date));
return {
props: {
posts,
featuredposts
},
};
}